import { UserProgress } from "@/types";
import {
  Footprints,
  Activity,
  Bot,
  Heart,
  Sprout,
  Flame,
  Rocket,
  Star,
  Target,
  Trophy,
  Crown,
  Gem,
  Map,
  Percent,
  Sparkles,
  BookOpen,
  GraduationCap,
  BookText,
  Medal,
  Zap,
  Calendar,
  Clock,
  Brain,
  Gamepad2,
  TrendingUp,
  Award,
  Shield,
  Lightbulb,
  Compass,
  Timer,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const ACHIEVEMENTS: Array<{
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  points: number;
  condition: (p: UserProgress) => boolean;
}> = [
  // JUEGOS JUGADOS
  {
    id: "first_steps",
    name: "Primeros Pasos",
    description: "Completa tu primer juego",
    icon: Footprints,
    points: 50,
    condition: (p) => p.games_played >= 1,
  },
  {
    id: "frequent_player",
    name: "Estudiante Constante",
    description: "Juega 10 veces",
    icon: Activity,
    points: 100,
    condition: (p) => p.games_played >= 10,
  },
  {
    id: "addict_player",
    name: "Máquina de Aprender",
    description: "Juega 50 veces",
    icon: Bot,
    points: 300,
    condition: (p) => p.games_played >= 50,
  },
  {
    id: "century_club",
    name: "Club de la Centuria",
    description: "Juega 100 veces",
    icon: Gamepad2,
    points: 500,
    condition: (p) => p.games_played >= 100,
  },
  {
    id: "super_fan",
    name: "Juego Favorito",
    description: "Juega el mismo juego 20 veces",
    icon: Heart,
    points: 200,
    condition: (p) => Object.values(p.game_stats || {}).some((g) => g.timesPlayed >= 20),
  },
  {
    id: "all_games",
    name: "Explorador",
    description: "Juega todos los juegos disponibles",
    icon: Compass,
    points: 200,
    condition: (p) => Object.keys(p.game_stats || {}).length >= 8,
  },

  // RACHAS
  {
    id: "streak_3",
    name: "Racha de 3 días",
    description: "Juega 3 días seguidos",
    icon: Sprout,
    points: 100,
    condition: (p) => p.streak >= 3,
  },
  {
    id: "streak_7",
    name: "Racha de 7 días",
    description: "Juega 7 días seguidos",
    icon: Flame,
    points: 150,
    condition: (p) => p.streak >= 7,
  },
  {
    id: "streak_14",
    name: "Racha de 14 días",
    description: "Juega 14 días seguidos",
    icon: Rocket,
    points: 300,
    condition: (p) => p.streak >= 14,
  },
  {
    id: "streak_30",
    name: "Racha de 30 días",
    description: "Juega 30 días seguidos",
    icon: Calendar,
    points: 500,
    condition: (p) => p.streak >= 30,
  },
  {
    id: "streak_60",
    name: "Guerrero Semestral",
    description: "Juega 60 días seguidos",
    icon: Shield,
    points: 1000,
    condition: (p) => p.streak >= 60,
  },
  {
    id: "streak_100",
    name: "Leyenda Viviente",
    description: "Juega 100 días seguidos",
    icon: Crown,
    points: 2000,
    condition: (p) => p.streak >= 100,
  },

  // PUNTOS
  {
    id: "points_500",
    name: "500 Puntos",
    description: "Alcanza 500 puntos totales",
    icon: Target,
    points: 50,
    condition: (p) => p.total_points >= 500,
  },
  {
    id: "points_1000",
    name: "1000 Puntos",
    description: "Alcanza 1000 puntos totales",
    icon: Trophy,
    points: 100,
    condition: (p) => p.total_points >= 1000,
  },
  {
    id: "points_5000",
    name: "5000 Puntos",
    description: "Alcanza 5000 puntos totales",
    icon: Crown,
    points: 500,
    condition: (p) => p.total_points >= 5000,
  },
  {
    id: "points_10000",
    name: "Leyenda del Inglés",
    description: "Alcanza 10000 puntos totales",
    icon: Gem,
    points: 1000,
    condition: (p) => p.total_points >= 10000,
  },
  {
    id: "points_25000",
    name: "Maestro Supremo",
    description: "Alcanza 25000 puntos totales",
    icon: Sparkles,
    points: 2500,
    condition: (p) => p.total_points >= 25000,
  },

  // EXPLORACIÓN Y RENDIMIENTO
  {
    id: "perfect_game",
    name: "Perfección",
    description: "Obtén 100% en un juego",
    icon: Percent,
    points: 150,
    condition: (p) => Object.values(p.game_stats || {}).some((g) => g.bestScore === 100),
  },
  {
    id: "five_perfect_games",
    name: "Maestro Impecable",
    description: "Obtén 100% en 5 juegos diferentes",
    icon: Award,
    points: 400,
    condition: (p) => Object.values(p.game_stats || {}).filter((g) => g.bestScore === 100).length >= 5,
  },
  {
    id: "ten_perfect_games",
    name: "Perfeccionista",
    description: "Obtén 100% en 10 juegos diferentes",
    icon: Medal,
    points: 800,
    condition: (p) => Object.values(p.game_stats || {}).filter((g) => g.bestScore === 100).length >= 10,
  },
  {
    id: "speed_learner",
    name: "Aprendiz Veloz",
    description: "Obtén más de 80% en un juego en menos de 30 segundos",
    icon: Timer,
    points: 300,
    condition: (p) => Object.values(p.game_stats || {}).some((g) => g.bestScore >= 80),
  },

  // NIVELES
  {
    id: "vocab_a1_master",
    name: "Vocabulario A1",
    description: "Completa el 50% de A1",
    icon: BookOpen,
    points: 100,
    condition: (p) => (p.level_progress?.A1?.completed || 0) >= 50,
  },
  {
    id: "level_a1",
    name: "Nivel A1",
    description: "Completa el nivel A1",
    icon: GraduationCap,
    points: 300,
    condition: (p) => (p.level_progress?.A1?.completed || 0) >= 100,
  },
  {
    id: "level_a2",
    name: "Nivel A2",
    description: "Completa el nivel A2",
    icon: BookText,
    points: 400,
    condition: (p) => (p.level_progress?.A2?.completed || 0) >= 100,
  },
  {
    id: "level_b1",
    name: "Nivel B1",
    description: "Completa el nivel B1",
    icon: Medal,
    points: 500,
    condition: (p) => (p.level_progress?.B1?.completed || 0) >= 100,
  },
  {
    id: "level_b2_learner",
    name: "Avanzando a B2",
    description: "Completa el 50% de B1",
    icon: Brain,
    points: 600,
    condition: (p) => (p.level_progress?.B1?.completed || 0) >= 150,
  },

  // CONSTANCIA Y MEJORA
  {
    id: "improver",
    name: "Buscador de Mejora",
    description: "Mejora tu puntuación en un juego 3 veces",
    icon: TrendingUp,
    points: 250,
    condition: (p) => Object.values(p.game_stats || {}).length >= 3,
  },
  {
    id: "dedicated",
    name: "Estudiante Dedicado",
    description: "Juega al menos una partida cada día por una semana",
    icon: Lightbulb,
    points: 350,
    condition: (p) => p.streak >= 7,
  },
];
